import datetime
a = datetime.datetime.now()
print(a)
print(a.strftime("%a"))
print(a.strftime("%A	"))
print(a.strftime("%w"))
print(a.strftime("%d"))
print(a.strftime("%b"))
print(a.strftime("%B"))
print(a.strftime("%m"))
print(a.strftime("%y"))
print(a.strftime("%Y"))
print(a.strftime("%H"))
print(a.strftime("%I"))
print(a.strftime("%p"))
print(a.strftime("%M"))
print(a.strftime("%S"))
print(a.strftime("%f"))
print(a.strftime("%z"))
print(a.strftime("%Z"))
print(a.strftime("%j"))
print(a.strftime("%U"))
print(a.strftime("%W"))
print(a.strftime("%c"))
print(a.strftime("%C"))
print(a.strftime("%x"))
print(a.strftime("%X"))
print(a.strftime("%%"))
print(a.strftime("%G"))
print(a.strftime("%u"))
print(a.strftime("%V"))





